on: [push]

jobs:
   public_test:
     runs-on: ubuntu-latest
     name: Install Bats common libs
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Setup BATS
         uses: mig4/setup-bats@v1
         with:
           bats-version: 1.5.0
       - name: Setup Bats libs
         uses: brokenpip3/setup-bats-libs@0.0.3
         with:
           support-clean: "false"
           assert-clean: "false"
           detik-clean: "false"
       - name: Execute test to check Bats-support
         run: |
          cd /tmp/bats-support/
          bats test
       - name: Execute test to check  Bats-assert
         run: |
          cd /tmp/bats-assert/
          sed "s:load \"${BATS_TEST_DIRNAME}.*:load \"/usr/lib/bats-assert\":g" test/test_helper.bash
          bats test
       - name: Execute test to check Bats-detik
         run: |
          cd /tmp/bats-detik/
          bats tests
